language: ruby
install:
- bundle install
- npm install -g fis
- npm install -g fis-postpackager-simple
- npm install -g fis-optimizer-html-minifier
script: bundle exec rake site:deploy
branches:
  only:
  - master
cache:
- bundler
- npm
env:
  global:
    secure: Vtm8/KFWPPrczMkezlmROewru/H4C7sL3ptR14wetP0v6pwuFl51xTV9QMforUa7EaI838griM4WLMGL1wHv7N1buDHocWGshJXwbXHQK8fm5F2q3CmcJe01zpBKhEtiP8ySci0MeGVuEDH16omIjIUzMlkFkLVUS/0QXcPyc/o=
